import { ExternalServiceError } from './errors';

export interface RecaptchaResponse {
  success: boolean;
  score: number;
}

/**
 * Verifies a reCAPTCHA v3 token.
 * 
 * @param token - The reCAPTCHA token generated by the client
 * @returns An object containing the success status and the score (0.0 to 1.0)
 */
export async function verifyRecaptcha(token: string): Promise<RecaptchaResponse> {
  if (!token) {
    return { success: false, score: 0 };
  }

  // If we're in a test environment, mock the response
  if (process.env.NODE_ENV === 'test') {
    if (token === 'valid_token') {
      return { success: true, score: 0.9 };
    }
    if (token === 'bot_token') {
      return { success: true, score: 0.1 };
    }
    return { success: false, score: 0 };
  }

  try {
    const secretKey = process.env.RECAPTCHA_SECRET_KEY;
    if (!secretKey) {
      console.warn('RECAPTCHA_SECRET_KEY is not set. Passing verification for development.');
      return { success: true, score: 1.0 };
    }

    const response = await fetch(`https://www.google.com/recaptcha/api/siteverify`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: `secret=${secretKey}&response=${token}`,
    });

    const data = await response.json();
    
    return {
      success: data.success === true,
      score: typeof data.score === 'number' ? data.score : 0,
    };
  } catch (error) {
    throw new ExternalServiceError('Failed to verify reCAPTCHA token');
  }
}
